/**
 * Indian States, Union Territories & Districts Data System
 * Provides comprehensive dropdown selection options for Indian address forms.
 */

export const INDIAN_STATES: string[] = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const STATE_DISTRICTS: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Guntur',
    'Vijayawada',
    'Visakhapatnam',
    'Tirupati',
    'Kurnool',
    'Nellore',
    'Kakinada',
    'Anantapur',
    'Chittoor',
    'Prakasam',
    'Kadapa',
    'Eluru',
    'Vizianagaram',
    'Srikakulam',
    'Nandyal',
    'Palnadu',
    'Bapatla',
    'Anakapalli',
    'Kona Seema',
  ],
  Telangana: [
    'Hyderabad',
    'Rangareddy',
    'Medchal-Malkajgiri',
    'Warangal',
    'Karimnagar',
    'Nizamabad',
    'Khammam',
    'Nalgonda',
    'Sangareddy',
    'Siddipet',
    'Mahabubnagar',
    'Adilabad',
    'Suryapet',
    'Mancherial',
    'Kamareddy',
  ],
  Karnataka: [
    'Bengaluru Urban',
    'Bengaluru Rural',
    'Mysuru',
    'Mangaluru (Dakshina Kannada)',
    'Hubballi-Dharwad',
    'Belagavi',
    'Kalaburagi',
    'Tumakuru',
    'Udupi',
    'Shivamogga',
    'Ballari',
    'Davangere',
    'Hassan',
    'Mandya',
    'Chikkamagaluru',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Tirunelveli',
    'Kanchipuram',
    'Chengalpattu',
    'Thanjavur',
    'Dindigul',
    'Cuddalore',
    'Kanyakumari',
  ],
  Maharashtra: [
    'Mumbai City',
    'Mumbai Suburban',
    'Pune',
    'Thane',
    'Nagpur',
    'Nashik',
    'Chhatrapati Sambhajinagar',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Navi Mumbai',
    'Pimpri-Chinchwad',
    'Satara',
    'Ahmednagar',
    'Sangli',
  ],
  Delhi: [
    'New Delhi',
    'Central Delhi',
    'East Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
    'Shahdara',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
    'Anand',
    'Bharuch',
    'Mehsana',
    'Valsad',
    'Navsari',
    'Morbi',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi (Ernakulam)',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Kannur',
    'Kottayam',
    'Alappuzha',
    'Palakkad',
    'Malappuram',
    'Wayanad',
    'Idukki',
    'Kasaragod',
    'Pathanamthitta',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'North 24 Parganas',
    'South 24 Parganas',
    'Hooghly',
    'Darjeeling',
    'Siliguri',
    'Paschim Bardhaman',
    'Purba Medinipur',
    'Bankura',
    'Murshidabad',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Gautam Buddha Nagar (Noida)',
    'Ghaziabad',
    'Varanasi',
    'Agra',
    'Prayagraj',
    'Bareilly',
    'Aligarh',
    'Gorakhpur',
    'Mathura',
    'Meerut',
    'Moradabad',
    'Jhansi',
    'Ayodhya',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bhilwara',
    'Sikar',
    'Sri Ganganagar',
    'Bharatpur',
    'Pali',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Gwalior',
    'Jabalpur',
    'Ujjain',
    'Sagar',
    'Satna',
    'Rewa',
    'Ratlam',
    'Dewas',
  ],
  Punjab: [
    'Chandigarh',
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Mohali (SAS Nagar)',
    'Bathinda',
    'Hoshiarpur',
    'Pathankot',
  ],
  Haryana: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Karnal',
    'Rohtak',
    'Hisar',
    'Sonipat',
    'Panchkula',
    'Rewari',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Muzaffarpur',
    'Bhagalpur',
    'Darbhanga',
    'Purnia',
    'Arrah (Bhojpur)',
    'Begusarai',
    'Katihar',
    'Nalanda',
  ],
  Odisha: [
    'Bhubaneswar (Khordha)',
    'Cuttack',
    'Rourkela (Sundargarh)',
    'Puri',
    'Sambalpur',
    'Balasore',
    'Berhampur (Ganjam)',
    'Bhadrak',
  ],
  Assam: [
    'Guwahati (Kamrup Metropolitan)',
    'Silchar (Cachar)',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur (Sonitpur)',
  ],
  Goa: ['North Goa', 'South Goa', 'Panaji', 'Margao', 'Vasco da Gama'],
  Chhattisgarh: ['Raipur', 'Bhilai (Durg)', 'Bilaspur', 'Korba', 'Rajnandgaon'],
  Jharkhand: ['Ranchi', 'Jamshedpur (East Singhbhum)', 'Dhanbad', 'Bokaro', 'Hazaribagh', 'Deoghar'],
  'Himachal Pradesh': ['Shimla', 'Dharamshala (Kangra)', 'Mandi', 'Solan', 'Kullu'],
  Uttarakhand: ['Dehradun', 'Haridwar', 'Haldwani (Nainital)', 'Roorkee', 'Rishikesh'],
};

/**
 * Returns available districts for a given state name.
 * If the current selected city is not in the predefined list, includes it as a custom entry so no user value is lost.
 */
export function getDistrictsForState(stateName: string, currentCity: string = ''): string[] {
  if (!stateName) {
    return currentCity ? [currentCity] : [];
  }

  const list = STATE_DISTRICTS[stateName] || [
    'Central District',
    'North District',
    'South District',
    'East District',
    'West District',
  ];

  if (currentCity && !list.includes(currentCity)) {
    return [currentCity, ...list];
  }
  return list;
}
